### ISSUE TITLE
long appeal names cut off

### ISSUE THREAD

**Issue by dalekunce** [IFRCGo/ifrcgo.github.io#22]
<img width="677" alt="screen shot 2017-03-09 at 11 22 47 am" src="https://cloud.githubusercontent.com/assets/1913857/23748270/cd3ae60a-04ba-11e7-9bc4-78ddc1fa3648.png">

Confirmed that its cut off in the site data.
<img width="1148" alt="screen shot 2017-03-09 at 11 23 59 am" src="https://cloud.githubusercontent.com/assets/1913857/23748315/fc730812-04ba-11e7-9f77-2e601e212bed.png">

**Comment by SimonbJohnson** [comment]
Problem is at source data from IFRC Business Objects.  I can't think of a suitable work around that is worth the effort.

**Comment by SimonbJohnson** [comment]
This appeal has now closed.  Will close this for now
