### ISSUE TITLE
Jekyll Refactor

### ISSUE THREAD

**Issue by dalekunce** [IFRCGo/ifrcgo.github.io#3]
Based on the work during the last sprint week we should move a lot of the pages to Jeykll. This is the basic list of new pages.

- [x] Appeal Home Page
   - [x] importer 
   - [x] updated page design/css/layout
- [ ] Appeals Pages
  - [x] importer 
   - [ ] updated page design/css/layout 
- [x] DREFs and Appeals
   - [ ] importer 
   - [x] updated page design/css/layout
- [x] Global RCRC 3W
  - [ ] importer 
   - [x] updated page design/css/layout 
- [x] Tools Readiness
  - [ ] importer 
   - [x] updated page design/css/layout 
- [x] Historic DREFs & Appeals
  - [ ] importer 
   - [x] updated page design/css/layout 

Steps we need to do complete them:

- [x] New gSheet formatted for appeals (csv output) @SimonbJohnson 
- [x] Jekyll importer of csv as part of gulpfile.js @dalekunce

**Comment by SimonbJohnson** [comment]
@dalekunce, Here is the link to the csv https://beta.proxy.hxlstandard.org/data/r_Jouy/download/appealplus.csv

Let me know if you the data structure isn't right.

We might hit a bit of a snag where the files are coming from a different source: https://proxy.hxlstandard.org/data/edit?url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1gJ4N_PYBqtwVuJ10d8zXWxQle_i84vDx5dHNBomYWdU%2Fedit%3Fusp%3Dsharing

We'll have the same problem with the optional modules, we could keep these as ajax queries?

**Comment by dalekunce** [comment]
@SimonbJohnson I'll investigate today and see what I can do.

**Comment by dalekunce** [comment]
@SimonbJohnson the JSON doesn't have a key:value structure. The current design isn't good json output and will difficult to parse.

when I go to https://beta.proxy.hxlstandard.org/data/r_Jouy/download/appealplus.json I expect to get 

``["#column": "data",
    "morecolumns": "moredata"]
``

instead the format is 
``["#column",
    "#morecolumns"],
   ["data",
    "moredata"]
``

**Comment by dalekunce** [comment]
@SimonbJohnson I think the quickest thing to do is to just get the csv and pipe it to json during the site build.

**Comment by SimonbJohnson** [comment]
@dalekunce Here's the function I used to convert

https://github.com/IFRCGo/IFRCGo.github.io/blob/master/js/index.js#L104-L127

**Comment by dalekunce** [comment]
No worries.

```
gulp.task('get-data', function() {
  var dlstream = download({
    file: "appealsplus.csv",
    url: "https://beta.proxy.hxlstandard.org/data/r_Jouy/download/appealplus.csv"
  })
  .pipe(gulp.dest("app/_data/temp"));

  dlstream.on('finish', function () {
    fs.createReadStream('app/_data/temp/appealsplus.csv')
      .pipe(csv2json({
        // Defaults to comma.
        separator: ','
      }))
      .pipe(
        fs.createWriteStream('app/_data/temp/appealsplus.json')
      );
  });

});```

One advantage of doing this is that we can reuse the same code if we need to authenticate in the future.

**Comment by dalekunce** [comment]
@SimonbJohnson appeals page is importing correctly. I also upgrade all of the dependencies on the site to the latest and greatest version to drop a lot of deprecation warnings and clean up npm. My import script now escapes all '#' and '+' in the appealsplus.csv, basically getting rid of the HXL encoding. For any JS functions you should still hit your version as the resulting appealsplus.json never makes it to the _site

- pull down all the latest changes
- update all your dependencies ``npm install``
- serve the new website ``gulp serve``
- home appeals page is in app/_includes/appeals.html
- each appeals page style is in app/_layouts/appeals.html
I've stubbed out a little bit of each page so you can see how it's pulled together

Page design and layout is now in @SimonbJohnson hands for appeals. I'll keep cleaning up the html templates that Simon makes to get them as streamlined as possible.

**Comment by dalekunce** [comment]
@SimonbJohnson @guidopiz what is the next page/todo you want me to work on.

**Comment by dalekunce** [comment]
@SimonbJohnson can we drop leaflet in favor of a straight d3 map option for the appeals pages. A full slippy map is more than we need if we just want to highlight the country on a worldmap. SVG would be way way faster. We could include a link to a full page map if people want to dive into it more.

**Comment by SimonbJohnson** [comment]
@dale, I was wondering in the future whether to allow people to add a basic layer about the disaster, such as a cyclone track to explore.  There has not been any requests for it yet though so happy to d3 it for now if you think it still makes sense.  I like your idea of a separate web page map per disaster though.

**Comment by SimonbJohnson** [comment]
@dalekunce as for the next page the current appeals is the next most used.
<img width="657" alt="screen shot 2016-11-23 at 12 32 27" src="https://cloud.githubusercontent.com/assets/2110742/20561934/f702f9fe-b178-11e6-8c9d-f42dcf18fe21.png">

**Comment by dalekunce** [comment]
Thinking about the map for each disaster. It could be pretty awesome to have something integrated wtih GeoNode/Carto or similar that SIMS could put a url in to display a map(s) with more information. I would imagine this could be supported via some CMS (google sheet or better) to publish the urls.

**Comment by SimonbJohnson** [comment]
I like this idea, it could be a webmap url as you say that cascades back to the simpler svg.  I'll add to the the to - do list :/

**Comment by dalekunce** [comment]
still need to configure the appeals pages to work with the jekyll data instead of HXL proxy requests.
