### ISSUE TITLE
Current Appeals CSV download sets today date at Sep 1 2016

### ISSUE THREAD

**Issue by ryales** [IFRCGo/ifrcgo.github.io#66]
The HXL proxy links for download from the Current Appeals dashboard (both global and regional) downloads data with an end date set to Sep 1, 2016 -- which is not today... The status of the appeals is also then not up to date when you download the data, which means every download gives you incorrect "active" appeals from months ago

https://proxy.hxlstandard.org/data.csv?strip-headers=on&filter03=merge&merge-url03=https%3A//docs.google.com/spreadsheets/d/1rVAE8b3uC_XIqU-eapUGLU7orIzYSUmvlPm9tI0bCbU/edit%23gid%3D0&clean-date-tags01=%23date&filter02=select&merge-keys03=%23meta%2Bid&filter04=replace-map&select-query06-01=%23region%3DEurope&filter05=merge&merge-tags03=%23meta%2Bcoverage%2C%23meta%2Bfunding&force=on&merge-keys05=%23country%2Bname&merge-tags05=%23country%2Bcode&filter01=clean&replace-map-url04=https%3A//docs.google.com/spreadsheets/d/1hTE0U3V8x18homc5KxfA7IIrv1Y9F1oulhJt0Z4z3zo/edit%3Fusp%3Dsharing&filter06=select&merge-url05=https%3A//docs.google.com/spreadsheets/d/1GugpfyzridvfezFcDsl6dNlpZDqI8TQJw-Jx52obny8/edit%3Fusp%3Dsharing&select-query02-01=%23date%2Bend%3E2016-09-01&url=https%3A//docs.google.com/spreadsheets/d/19pBx2NpbgcLFeWoJGdCqECT2kw9O9_WmcZ3O41Sj4hU/edit%23gid%3D0

Create dynamic download url link with an end date of TODAY() or equivalent of this

**Comment by SimonbJohnson** [comment]
@ryales, fixed here d07a19cd3772b5273c6e80eb7df9c53cbcfbefe9

Will be in the next deploy to production

Unfortunately, the 'active' column is maintained by the IFRC and very out of date and I don't think Go has any say on it.

@renecnielsen shall we just cut it from our data downloads?

**Comment by renecnielsen** [comment]
Yes, please @SimonbJohnson . One would think that #date+end should do the trick quite nicely.

Thanks for reporting this, @ryales!
