### ISSUE TITLE
Missing countries in Europe

### ISSUE THREAD

**Issue by ryales** [IFRCGo/ifrcgo.github.io#75]
I know you have plans to move the map to SVG, so not sure if this is relevant for long, but FYI when you do not include Malta, San Marino, Liechtenstein and Monaco in the world map on the launch page. Those are countries with NSs so please ensure they are included in the next round of maps :)

**Comment by SimonbJohnson** [comment]
Good spot!  Will update the geom when I'm back later this month.

**Comment by toffehoff** [comment]
While you're at it. Please make sure Somalia and Somaliland are one country.

**Comment by SimonbJohnson** [comment]
@ryales do you have a latest version that we should build off?

**Comment by ryales** [comment]
@SimonbJohnson do you mean a 

file for the geom? Here I made one for you -- Natural Earth 50m -- the 100m cuts out the countries as described above. I also edited it to merge Somalia and Somaliland under the iso SOM. If you want to simplify further with mapshaper be sure to not eliminate shapes and that should solve the issue :) Thanks!
[ne_50m_admin_0_countries_edited.zip](https://github.com/IFRCGo/ifrcgo.github.io/files/1209572/ne_50m_admin_0_countries_edited.zip)

**Comment by renecnielsen** [comment]
Great work, @ryales and @SimonbJohnson! Can't wait for this one to be sorted...
